### ISSUE TITLE
storybook

### ISSUE THREAD

**Issue by matt-erhart** [RyanCCollins/scalable-react-ts-boilerplate#18]
Would be great to have https://github.com/storybooks/react-storybook built into this starter. The part I'm not sure how to do is the webpack config as shown here: https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config.

**Comment by StevenTCramer** [comment]
https://github.com/griddlegriddle/griddle   Uses storybook and webpack.  What are you thinking as the use case in this starter?

**Comment by RyanCCollins** [comment]
Yeah storybook would be pretty cool to have!  I will add it to the [roadmap](https://github.com/scalable-react/scalable-react-typescript-boilerplate/blob/master/README.md#roadmap).

@matt-erhart we are definitely looking for help, so if that's something you'd like to work on it would be very much appreciated.  I can see about helping with the webpack configuration.  I'll come back to this later tonight.

**Comment by RyanCCollins** [comment]
Hey @matt-erhart, I've added storybook and it should be on master later today.  We could definitely use some help writing stories for the reusable components.  If you are still interested in helping, that'd be a great place to start.

Thanks again for your input!
