### ISSUE TITLE
jest-haste-map: duplicate manual mock found

### ISSUE THREAD

**Issue by scottf-git** [RyanCCollins/scalable-react-ts-boilerplate#35]
I'm starting to see this when I run tests:

`$ yarn test
yarn test v0.21.2
$ cross-env NODE_ENV=test jest
jest-haste-map: duplicate manual mock found:
  Module name: headingProps.mocks
  Duplicate Mock path: C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Heading\__tests__\__mocks__\headingProps.mocks.js
This warning is caused by two manual mock files with the same file name.
Jest will use the mock file found in:
C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Heading\__tests__\__mocks__\headingProps.mocks.js
 Please delete one of the following two files:
 C:\Git\scalable-react-typescript-boilerplate\src\client\components\Heading\__tests__\__mocks__\headingProps.mocks.ts
C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Heading\__tests__\__mocks__\headingProps.mocks.js

jest-haste-map: duplicate manual mock found:
  Module name: headlineProps.mocks
  Duplicate Mock path: C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Headline\__tests__\__mocks__\headlineProps.mocks.js
This warning is caused by two manual mock files with the same file name.
Jest will use the mock file found in:
C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Headline\__tests__\__mocks__\headlineProps.mocks.js
 Please delete one of the following two files:
 C:\Git\scalable-react-typescript-boilerplate\src\client\components\Headline\__tests__\__mocks__\headlineProps.mocks.ts
C:\Git\scalable-react-typescript-boilerplate\build\src\client\components\Headline\__tests__\__mocks__\headlineProps.mocks.js
`

**Comment by RyanCCollins** [comment]
Thanks for catching this!  The problem was that a few of the mocks were being transpiled by ts.  This is now fixed.
