### ISSUE TITLE
Problem doing npm install

### ISSUE THREAD

**Issue by murugaratham** [RyanCCollins/scalable-react-ts-boilerplate#44]
`(58,24): error TS2345: Argument of type 'History' is not assignable to parameter of type 'History'.
  Types of property 'createLocation' are incompatible.
    Type '{ (path?: LocationDescriptor, action?: string, key?: string): Location; (path?: string, state?: O...' is not assignable to type '(path?: LocationDescriptor, action?: Action, key?: string) => Location'.
      Type 'Location' is not assignable to type 'Location'. Two different types with this name exist, but they are unrelated.
        Types of property 'action' are incompatible.
          Type 'string' is not assignable to type 'Action'.`

Not sure if it's due to typings [https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14575](url)

> If anyone is interested, I have solved the problem by adding the last version of @types/history to package.json then delete node_modules and re-install.

> Hope it will work for you as it did for me. ❤️

**Comment by RyanCCollins** [comment]
Nice! Thank you for sharing!

We have recommended using yarn for this reason.  It seems npm can sometimes drift, while yarn is deterministic in its approach.

If you get a chance, please feel free to submit a PR with the updated packages.

Thank you again!

**Comment by RyanCCollins** [comment]
I am going to close this because you were able to resolve it, but please feel free to keep the conversation going if needed.
